services:
  db:
    image: bitnami/postgresql:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
      - db:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    restart: unless-stopped
    container_name: brevly-server
    ports:
      - $PORT:$PORT
    environment:
      - DATABASE_URL=$DATABASE_URL
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL

volumes:
  db:
  